### ISSUE TITLE
da download

### ISSUE THREAD

**Issue by Inflector0riginal** [Def-Try/CustomMusic#1]
it's not downloading,fix pls

**Comment by Def-Try** [comment]
hhhhh

**Comment by Def-Try** [comment]
try now, it should be fixed

**Comment by Inflector0riginal** [comment]
5 minutes i tried to download the mod,sorry but you didn't fix,what's the problem? with file's? or with code in the mod?

**Comment by Def-Try** [comment]
any download error? can it say somenthing like "could not access repo" or no?

**Comment by Inflector0riginal** [comment]
No, no errors, it's just a loading screen, it always stays at %0 loading
